name: recipers
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.5.20
  shared_preferences: ^0.5.0
  http: ^0.12.0+1
  flutter_webview_plugin: ^0.3.0+2
  url_launcher:
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  image_path: 'images/app_icon.png'
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/reciper.png
  - images/recipers.png
  - images/recipers-subtitle.png
  - images/ricebowl-item.jpg
  - images/southindianthali.jpg
  - images/dosa.jpg
  - images/thali.jpg
  - images/delivery_boy.jpg
  - images/get_faster.jpg
  - images/face.jpg
  - images/preloader-logo.jpg
  - images/profile.png
  - images/people.jpg
  - images/cashback.png
  - images/paytm.png
  - images/gpay.png
  - images/phonepe.jpg
  - images/foodtrail.gif
  - images/honeychilli.jpg
  - images/gobifriedrice.jpg
  - images/munchrianfriedrice.jpg
  - images/chanasamosa.png
  - images/chanakachori.jpg
  - images/kiwijuice.jpg
  - images/orange.png
  - images/pineapple.jpg
  - images/dominospizza.jpg
  - images/choclatejuices.jpg
  - images/punugulu.jpg
  - images/Uthappam.jpg
  - images/upma.png
  - images/parantha.jpg
  - images/noodels.jpg
  - images/poha.jpg
  - images/bajji.jpg
  - images/Mysore-Bonda-Recipe.jpg
  - images/puri.jpg
  - images/Hyderabadi-biryani-7.jpg
  - images/tomatorice.jpg
  - images/Curd_Rice.jpg
  - images/parota.jpg
  - images/paneertikka.jpg
  - images/burger.jpg
  - images/frenchfrice.jpg
  - images/sandwich.jpg 
  - images/garlicrice.jpg
  - images/mushroom.png
  - images/gobi-manchurian.jpg
  - images/Mexican-Spring-Rolls-1-1-500x375.jpg
  - images/juice.jpg
  - images/idlis.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Questrial
    fonts:
    - asset: fonts/Questrial/Questrial-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  - family: SanFranciscoFont
    fonts:
    - asset: fonts/SanFranciscoFont/SFProDisplay-Regular.ttf
  - family: Google-Sans-Font
    fonts:
    - asset: fonts/Google-Sans-Font/GoogleSans-Regular.ttf
  - family: Nunitno
    fonts:
    - asset: fonts/Nunito/Nunito-SemiBold.ttf
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat/Montserrat-Regular.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages